'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { useWorkspace } from '@/components/workspace-context';
import { Button, Card, Empty, ErrorBox, Field, Input, Kpi, Loading, Pill, Select, Textarea } from '@/components/ui';
import { api } from '@/lib/api';
import { tt, type TTAccount, type TTDraft, type TTVideo, type TTAnalytics, type TTAnalysis } from '@/lib/tiktok';
const blank = { title: '', caption: '', hook: '', script: '', hashtags: '', sourceUrl: '' };
const num = (v: number | null | undefined) => v == null ? tt.unavailable : v.toLocaleString('th-TH');
export default function TikTokPage() { const { ws } = useWorkspace(); return <TikTokWorkspace key={ws.id} />; }
function TikTokWorkspace() {
  const { ws, can } = useWorkspace(); const base = `/workspaces/${ws.id}/tiktok`;
  const [accounts, setAccounts] = useState<TTAccount[] | null>(null); const [health, setHealth] = useState<{ configured: boolean; publishingEnabled: boolean } | null>(null);
  const [brands, setBrands] = useState<{ id: string; name: string }[]>([]); const [brandId, setBrandId] = useState(''); const [scopes, setScopes] = useState({ profile: false, stats: false, upload: false });
  const [tab, setTab] = useState('accounts'); const [accountId, setAccountId] = useState(''); const [videos, setVideos] = useState<TTVideo[]>([]); const [analytics, setAnalytics] = useState<TTAnalytics | null>(null); const [analysis, setAnalysis] = useState<TTAnalysis | null>(null);
  const [drafts, setDrafts] = useState<TTDraft[]>([]); const [sources, setSources] = useState<{ id: string; title: string; platform: string }[]>([]); const [task, setTask] = useState('ideas'); const [brief, setBrief] = useState(''); const [source, setSource] = useState('');
  const [form, setForm] = useState(blank); const [editId, setEditId] = useState(''); const [reviewed, setReviewed] = useState(false); const [local, setLocal] = useState(''); const [timezone, setTimezone] = useState(ws.timezone);
  const [busy, setBusy] = useState(false); const [error, setError] = useState<unknown>(null); const [notice, setNotice] = useState('');
  const initialized = useRef(false);
  const load = useCallback(async () => {
    const [h, a, d, b] = await Promise.all([api<{ configured: boolean; publishingEnabled: boolean }>(`${base}/health`), api<TTAccount[]>(`${base}/accounts`), api<TTDraft[]>(`${base}/content`), api<{ id: string; name: string; client: { name: string } }[]>(`${base}/brands`)]);
    setHealth(h); setAccounts(a); setDrafts(d); setBrands(b.map(x => ({ id: x.id, name: `${x.client.name} / ${x.name}` })));
    if (!initialized.current) { const first = a.find(x => x.status === 'ACTIVE'); setAccountId(first?.id || ''); setBrandId(first?.brandId || b[0]?.id || ''); initialized.current = true; }
  }, [base]);
  useEffect(() => { void load().catch(setError);
    const connection = new URLSearchParams(window.location.search).get('connection'); if (connection) setNotice(connection === 'connected' ? tt.connected : tt.connectionFailed);
  }, [load]);
  useEffect(() => {
    let active = true; setSources([]); setSource('');
    if (brandId && can('content.read') && can('tiktok.content.create')) void api<{ id: string; title: string; platform: string }[]>(`${base}/brands/${brandId}/sources`).then(s => { if (active) setSources(s); }).catch(e => { if (active) setError(e); });
    return () => { active = false; };
  }, [base, brandId, can]);
  useEffect(() => {
    let active = true; setVideos([]); setAnalytics(null); setAnalysis(null);
    if (tab === 'videos' && accountId) void Promise.all([api<TTVideo[]>(`${base}/accounts/${accountId}/videos`), api<TTAnalytics>(`${base}/accounts/${accountId}/analytics`)]).then(([v, a]) => { if (active) { setVideos(v); setAnalytics(a); } }).catch(e => { if (active) setError(e); });
    return () => { active = false; };
  }, [accountId, base, tab]);
  const run = async (f: () => Promise<unknown>) => { setBusy(true); setError(null); setNotice(''); try { const result = await f(); if (result && typeof result === 'object' && 'revokeStatus' in result && result.revokeStatus === 'LOCAL_DISCONNECT_ONLY') setNotice(tt.localDisconnected); else if (result && typeof result === 'object' && 'status' in result) setNotice(tt.status[String(result.status)] || String(result.status)); else setNotice(tt.saved); await load(); } catch (e) { setError(e); } finally { setBusy(false); } };
  const edit = (d: TTDraft) => { setEditId(d.id); setAccountId(d.tiktokAccountId || ''); setBrandId(d.tiktokBrandId); setReviewed(false); setForm({ title: d.title, caption: d.caption, hook: d.tiktokMeta.hook || '', script: d.tiktokMeta.script || '', hashtags: d.hashtags.join(' '), sourceUrl: d.tiktokMeta.sourceUrl || '' }); };
  if (!accounts || !health) return <div><ErrorBox error={error} /><Loading /></div>;
  const download = async (id: string) => {
    const result = await api<{ filename: string; text: string }>(`${base}/content/${id}/export`);
    const url = URL.createObjectURL(new Blob(['\ufeff' + result.text], { type: 'text/plain;charset=utf-8' }));
    const link = document.createElement('a'); link.href = url; link.download = result.filename; document.body.appendChild(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  };
  return <div className="space-y-5">
    <div><h1 className="text-2xl font-semibold">{tt.title}</h1><p className="text-sm text-slate-400">{tt.subtitle}</p></div>
    <ErrorBox error={error} />{notice && <p role="status" className="rounded-lg border border-sky-500/30 p-3 text-sm">{notice}</p>}
    {!health.configured && <Empty text={tt.notConfigured} />}
    {!health.publishingEnabled && <p className="rounded-lg bg-amber-950 p-3 text-sm text-amber-300">{tt.safeMode}</p>}
    <div className="flex gap-2">{(['accounts', 'videos', 'studio'] as const).map(v => <Button key={v} variant={v === tab ? 'primary' : 'ghost'} onClick={() => { setError(null); setTab(v); }}>{tt[v]}</Button>)}</div>
    {tab === 'accounts' ? <>
      {can('tiktok.connect') && <Card title={tt.connect}><div className="grid gap-3 md:grid-cols-2"><Field label={tt.brand}><Select value={brandId} onChange={e => setBrandId(e.target.value)}><option value="">{tt.chooseBrand}</option>{brands.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</Select></Field><div className="flex flex-wrap items-center gap-3">{(['profile', 'stats', 'upload'] as const).map(k => <label key={k} className="text-sm"><input type="checkbox" checked={scopes[k]} onChange={e => setScopes(s => ({ ...s, [k]: e.target.checked }))} /> {k === 'upload' ? tt.uploadScope : tt[k]}</label>)}</div><Button disabled={!health.configured || !brandId || busy} onClick={() => void run(async () => { const r = await api<{ url: string }>(`${base}/oauth/start`, { method: 'POST', body: { brandId, ...scopes } }); window.location.assign(r.url); })}>{tt.connect}</Button></div></Card>}
      {!accounts.length && <Empty text={tt.empty} />}
      {accounts.map(a => <Card key={a.id} title={`${a.displayName || a.username || 'TikTok'} · ${a.brand.name}`} actions={<Pill tone={a.status === 'ACTIVE' ? 'ok' : 'warn'}>{tt.status[a.status] || a.status}</Pill>}>
        <div className="mb-3 flex gap-3">{a.avatarUrl && <img src={a.avatarUrl} alt="" width={48} height={48} className="rounded-full" referrerPolicy="no-referrer" />}{a.username && <p>@{a.username}</p>}</div>
        <div className="grid grid-cols-2 gap-2 md:grid-cols-4">{(['followers', 'following', 'likes', 'videoCount'] as const).map(k => <Kpi key={k} label={tt[k]} value={num(a[k])} />)}</div>
        {a.lastError && <p className="my-2 text-sm text-rose-400">{a.lastError}</p>}
        <div className="mt-3 flex flex-wrap gap-2"><Button disabled={busy || a.status !== 'ACTIVE'} onClick={() => void run(() => api(`${base}/accounts/${a.id}/sync`, { method: 'POST', body: {} }))}>{tt.sync}</Button>{can('tiktok.connect') && <><Button variant="ghost" disabled={busy} onClick={() => void run(() => api(`${base}/accounts/${a.id}/pause`, { method: 'PATCH', body: { paused: !a.uploadsPaused } }))}>{a.uploadsPaused ? tt.resume : tt.pause}</Button><Button variant="danger" disabled={busy || a.status === 'DISCONNECTED'} onClick={() => { if (confirm(tt.disconnectConfirm)) void run(() => api(`${base}/accounts/${a.id}`, { method: 'DELETE' })); }}>{tt.disconnect}</Button></>}</div>
      </Card>)}
    </> : <>
      {tab === 'studio' && <><p className="text-sm text-slate-400">{tt.offlineHint}</p><Field label={tt.brand}><Select value={brandId} onChange={e => { setBrandId(e.target.value); setAccountId(''); setEditId(''); setReviewed(false); setForm(blank); }}><option value="">{tt.chooseBrand}</option>{brands.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</Select></Field>{!brands.length && <a href="/clients" className="text-sky-500">{tt.createBrand}</a>}</>}
      <Field label={tt.chooseAccount}><Select value={accountId} onChange={e => { setAccountId(e.target.value); const a = accounts.find(x => x.id === e.target.value); if (a) setBrandId(a.brandId); setEditId(''); setReviewed(false); setForm(blank); }}><option value="">{tab === 'studio' ? tt.noAccount : tt.chooseAccount}</option>{accounts.filter(a => tab !== 'studio' || a.brandId === brandId).map(a => <option key={a.id} value={a.id}>{a.displayName} · {a.brand.name}</option>)}</Select></Field>
      {tab === 'videos' ? <>
        {analytics && <><div className="grid gap-3 md:grid-cols-2"><Kpi label={tt.baseline} value={num(analytics.medianViews)} /><Kpi label={tt.sample} value={analytics.measuredSampleSize} /></div><p className="text-sm text-slate-400">{tt.comparison}</p></>}
        <Button disabled={!accountId || busy || !videos.length || !can('ai.use')} onClick={() => void run(async () => { setAnalysis(await api<TTAnalysis>(`${base}/accounts/${accountId}/analyze`, { method: 'POST', body: {} })); })}>{tt.analyze}</Button>
        {analysis && <Card title={tt.interpretation}><ul className="list-disc space-y-2 pl-5">{analysis.interpretation.interpretations.map((r, i) => <li key={i}>{r.text} <span className="text-xs text-slate-500">({r.evidenceVideoIds.map(id => videos.find(v => v.id === id)?.title || id).join(', ')})</span></li>)}</ul><h3 className="mt-4 font-semibold">{tt.recommendations}</h3>{analysis.interpretation.recommendations.map((r, i) => <p key={i}>{r.action}</p>)}<h3 className="mt-4 font-semibold">{tt.limitations}</h3>{analysis.interpretation.limitations.map((r, i) => <p key={i} className="text-sm text-slate-400">{r}</p>)}</Card>}
        {!videos.length && <Empty text={tt.emptyVideos} />}
        <div className="grid gap-3 lg:grid-cols-2">{videos.map(v => { const m = v.snapshots[0]; const score = analytics?.videos.find(x => x.id === v.id); return <Card key={v.id} title={v.title} actions={score?.highPerforming ? <Pill tone="ok">{tt.winner} {score.relativeViews?.toFixed(1)}×</Pill> : undefined}><div className="flex gap-3">{v.thumbnailUrl && <img src={v.thumbnailUrl} alt="" width={80} className="h-28 rounded object-cover" referrerPolicy="no-referrer" />}<div className="grid flex-1 grid-cols-2 gap-2 text-sm">{(['views', 'likes', 'comments', 'shares'] as const).map(k => <div key={k}>{tt[k]}: {num(m?.[k])}</div>)}{v.publishedAt && <time>{new Date(v.publishedAt).toLocaleDateString('th-TH')}</time>}{v.shareUrl && <a href={v.shareUrl} target="_blank" rel="noreferrer" className="text-sky-500">TikTok ↗</a>}</div></div></Card>; })}</div>
      </> : <>
        <p className="text-sm text-slate-400">{tt.inboxNotice}</p>
        {can('tiktok.content.create') && <>
          <Card title={tt.studio}><div className="grid gap-3 md:grid-cols-2"><Field label={tt.task}><Select value={task} onChange={e => setTask(e.target.value)}>{(['ideas', 'hook', 'script', 'caption', 'hashtags', 'repurpose'] as const).map(k => <option key={k} value={k}>{tt[k]}</option>)}</Select></Field>{task === 'repurpose' && <Field label={tt.source}><Select value={source} onChange={e => setSource(e.target.value)}><option value="">{tt.noSource}</option>{sources.map(s => <option key={s.id} value={s.id}>{s.platform} · {s.title}</option>)}</Select></Field>}<Field label={tt.brief}><Textarea value={brief} onChange={e => setBrief(e.target.value)} /></Field></div><Button className="mt-3" disabled={busy || !brief.trim() || !brandId || !can('ai.use')} onClick={() => void run(async () => { const d = await api<TTDraft>(`${base}/${accountId ? 'accounts/' + accountId : 'brands/' + brandId}/studio`, { method: 'POST', body: { task, brief, ...(source && { sourceContentId: source }) } }); edit(d); })}>{tt.generate}</Button></Card>
          <Card title={editId ? tt.edit : tt.newDraft}><form onSubmit={e => { e.preventDefault(); void run(async () => { const body = { ...form, hashtags: form.hashtags.split(/\s+/).filter(Boolean).map(h => h.replace(/^#/, '')) }; const d = await api<TTDraft>(`${base}/content${editId ? '/' + editId : ''}`, { method: editId ? 'PATCH' : 'POST', body: editId ? body : { ...body, brandId, ...(accountId && { accountId }) } }); edit(d); }); }} className="space-y-3"><div className="grid gap-3 md:grid-cols-2">{(['title', 'hook', 'caption', 'script', 'hashtags', 'sourceUrl'] as const).map(k => <Field key={k} label={k === 'title' ? tt.titleField : tt[k]} hint={k === 'sourceUrl' ? tt.mediaHint : undefined}>{['caption', 'script'].includes(k) ? <Textarea value={form[k]} onChange={e => setForm(f => ({ ...f, [k]: e.target.value }))} /> : <Input required={k === 'title'} type={k === 'sourceUrl' ? 'url' : 'text'} value={form[k]} onChange={e => setForm(f => ({ ...f, [k]: e.target.value }))} />}</Field>)}</div><Button disabled={busy || !brandId}>{tt.save}</Button><Button type="button" variant="ghost" onClick={() => { setEditId(''); setForm(blank); }}>{tt.newDraft}</Button></form></Card>
        </>}
        <Card title={tt.drafts}><label className="mb-3 block text-sm"><input type="checkbox" checked={reviewed} onChange={e => setReviewed(e.target.checked)} /> {tt.reviewed}</label><div className="mb-4 grid gap-3 md:grid-cols-2"><Field label={tt.scheduled}><Input type="datetime-local" value={local} onChange={e => setLocal(e.target.value)} /></Field><Field label={tt.timezone}><Input value={timezone} onChange={e => setTimezone(e.target.value)} /></Field></div>
          {!drafts.some(d => (!brandId || d.tiktokBrandId === brandId) && (!accountId || !d.tiktokAccountId || d.tiktokAccountId === accountId)) && <Empty text={tt.emptyDrafts} />}
          <div className="space-y-4">{drafts.filter(d => (!brandId || d.tiktokBrandId === brandId) && (!accountId || !d.tiktokAccountId || d.tiktokAccountId === accountId)).map(d => <article key={d.id} className="rounded-lg border border-slate-700 p-3"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{d.title}</h3><Pill>{tt.status[d.status] || d.status}</Pill>{!['DRAFT', 'READY'].includes(d.tiktokMeta.uploadStatus) && <Pill tone="warn">{tt.status[d.tiktokMeta.uploadStatus] || d.tiktokMeta.uploadStatus}</Pill>}{d.aiModel && <span className="text-xs">{d.aiModel}</span>}</div><p className="mt-2 text-xs text-slate-400">{d.tiktokBrand?.name} · {d.tiktokAccountId ? accounts.find(a => a.id === d.tiktokAccountId)?.displayName : tt.noAccount}</p><p className="my-2 whitespace-pre-wrap text-sm">{d.caption}</p><details><summary className="cursor-pointer text-sm text-sky-500">{tt.script}</summary><p className="whitespace-pre-wrap text-sm">{d.tiktokMeta.script}</p></details>{d.aiNotes?.missingFacts?.length ? <p className="my-2 text-sm text-amber-400">{tt.missing}: {d.aiNotes.missingFacts.join(', ')}</p> : null}{d.aiNotes?.ideas?.map((idea, i) => <p key={i} className="my-1 text-sm">{idea.title}: {idea.hook} — {idea.concept}</p>)}{d.lastError && <p className="text-sm text-rose-400">{d.lastError}</p>}{d.scheduledAt && <p className="text-xs">{tt.scheduled}: {new Date(d.scheduledAt).toLocaleString('th-TH')}</p>}
            <div className="mt-3 flex flex-wrap gap-2"><Button variant="ghost" disabled={busy} onClick={() => void run(() => download(d.id))}>{tt.download}</Button>{can('tiktok.content.create') && !d.tiktokAccountId && accountId && ['DRAFT', 'READY_FOR_APPROVAL', 'APPROVED', 'REJECTED'].includes(d.status) && <Button disabled={busy} onClick={() => void run(() => api(`${base}/content/${d.id}/account`, { method: 'PATCH', body: { accountId } }))}>{tt.assign}</Button>}{can('tiktok.content.create') && ['DRAFT', 'APPROVED', 'READY_FOR_APPROVAL', 'REJECTED', 'SCHEDULED'].includes(d.status) && <Button variant="ghost" disabled={busy} onClick={() => edit(d)}>{tt.edit}</Button>}{can('tiktok.content.create') && d.status === 'DRAFT' && <Button disabled={busy || !reviewed} onClick={() => void run(() => api(`${base}/content/${d.id}/submit`, { method: 'POST', body: { reviewed: true } }))}>{tt.submit}</Button>}{can('tiktok.content.approve') && d.status === 'READY_FOR_APPROVAL' && <><Button disabled={busy} onClick={() => void run(() => api(`${base}/content/${d.id}/decision`, { method: 'POST', body: { approve: true } }))}>{tt.approve}</Button><Button variant="danger" disabled={busy} onClick={() => void run(() => api(`${base}/content/${d.id}/decision`, { method: 'POST', body: { approve: false } }))}>{tt.reject}</Button></>}{can('tiktok.upload') && d.status === 'APPROVED' && <Button disabled={busy || !health.publishingEnabled || !d.tiktokAccountId} onClick={() => { if (confirm(tt.sendConfirm)) void run(() => api(`${base}/content/${d.id}/send`, { method: 'POST', body: { confirm: true, ...(local && { scheduledLocal: local, timezone }) } })); }}>{local ? tt.schedule : tt.send}</Button>}{['PUBLISH_PENDING', 'UPLOADED'].includes(d.tiktokMeta.uploadStatus) && <Button variant="ghost" disabled={busy} onClick={() => void run(() => api(`${base}/content/${d.id}/poll`, { method: 'POST', body: {} }))}>{tt.poll}</Button>}{can('tiktok.content.create') && ['DRAFT', 'APPROVED', 'SCHEDULED', 'READY_FOR_APPROVAL', 'REJECTED'].includes(d.status) && <Button variant="danger" disabled={busy} onClick={() => void run(() => api(`${base}/content/${d.id}`, { method: 'DELETE' }))}>{tt.cancel}</Button>}</div>
          </article>)}</div>
        </Card>
      </>}
    </>}
  </div>;
}
