import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { TikTokClient, TikTokError, videoSchema } from './client';
import { analyzeMetrics, validateMediaUrl } from './metrics';
import { startMockTikTok } from './mock';
describe('TikTok official protocol', () => {
  let mock: Awaited<ReturnType<typeof startMockTikTok>>; let client: TikTokClient;
  beforeAll(async () => { mock = await startMockTikTok(); client = new TikTokClient({ clientKey: 'client', clientSecret: 'secret', redirectUri: 'https://app.example/api/tiktok/oauth/callback', mockBaseUrl: mock.url, testMode: true }); });
  afterAll(() => { mock.server.closeAllConnections(); mock.server.close(); });
  it('uses official authorization URL and explicit scopes without secrets', () => { const u = new URL(client.authUrl('nonce', ['user.info.basic'])); expect(u.origin).toBe('https://www.tiktok.com'); expect(u.searchParams.get('scope')).toBe('user.info.basic'); expect(u.href).not.toContain('secret'); });
  it('rejects insecure web callbacks and non-test mock override', () => { expect(() => new TikTokClient({ mockBaseUrl: mock.url })).toThrow(); expect(() => new TikTokClient({ clientKey: 'a', clientSecret: 'b', redirectUri: 'http://localhost:3000/callback' }).authUrl('a', [])).toThrow(TikTokError); });
  it('exchanges form data, rotates refresh tokens and requests only granted fields', async () => { expect((await client.exchange('code')).refresh_token).toBe('REFRESH_SECRET_0'); expect((await client.refresh('REFRESH_SECRET_0')).refresh_token).toBe('REFRESH_SECRET_1'); await client.profile('ACCESS_SECRET', ['user.info.basic']); expect(mock.state.calls.at(-1)?.path).toBe('/v2/user/info/'); });
  it('handles pagination and unavailable metrics without zero substitution', async () => { const a = await client.videos('ACCESS_SECRET'); const b = await client.videos('ACCESS_SECRET', a.cursor); expect(a.has_more).toBe(true); expect(b.has_more).toBe(false); expect(b.videos[0]?.share_count).toBeNull(); expect(videoSchema.parse({ id: 'x' }).view_count).toBeNull(); });
  it('sanitizes provider errors including HTTP 200 errors and does not retry auth failures', async () => { const count = mock.state.calls.length; mock.state.error = 'access_token_invalid'; try { await expect(client.profile('ACCESS_SECRET', [])).rejects.toMatchObject({ code: 'access_token_invalid', needsReconnect: true }); expect(mock.state.calls.length).toBe(count + 1); } finally { mock.state.error = ''; } });
  it('bounds read retries on rate limits', async () => { const count = mock.state.calls.length; mock.state.httpStatus = 429; mock.state.error = 'rate_limit_exceeded'; try { await expect(client.videos('token')).rejects.toMatchObject({ code: 'rate_limit_exceeded' }); expect(mock.state.calls.length).toBe(count + 3); } finally { mock.state.error = ''; mock.state.httpStatus = 200; } });
  it('does not retry an uncertain upload initialization', async () => { mock.state.failInit = true; const before = mock.state.inits; try { await expect(client.uploadInbox('ACCESS_SECRET', 'https://media.example/video.mp4')).rejects.toMatchObject({ ambiguous: true }); expect(mock.state.inits).toBe(before + 1); } finally { mock.state.failInit = false; } });
});
describe('TikTok analytics and media', () => {
  it('requires an account baseline and sufficient sample', () => { const rows = [100, 100, 200, 100, 1000].map((views, i) => ({ id: String(i), views, likes: 10, comments: 5, shares: 5 })); const a = analyzeMetrics(rows); expect(a.medianViews).toBe(100); expect(a.videos[4]?.relativeViews).toBe(10); expect(a.videos[4]?.highPerforming).toBe(true); expect(analyzeMetrics(rows.slice(4)).videos[0]?.highPerforming).toBe(false); });
  it('preserves null and does not divide by zero', () => { const a = analyzeMetrics([{ id: 'x', views: 0, likes: null, comments: null, shares: null }]); expect(a.videos[0]?.engagementRate).toBeNull(); expect(a.videos[0]?.relativeViews).toBeNull(); expect(analyzeMetrics([]).medianViews).toBeNull(); });
  it('matches public HTTPS media prefix boundaries', () => { const prefixes = ['https://media.example/videos']; expect(validateMediaUrl('https://media.example/videos/a.mp4', prefixes)).toContain('a.mp4'); for (const u of ['https://media.example/videos-evil/a.mp4', 'https://media.example.evil/videos/a.mp4', 'http://media.example/videos/a.mp4', 'https://media.example/videos/a.mp4?token=x', 'https://127.0.0.1/videos/a.mp4']) expect(() => validateMediaUrl(u, prefixes)).toThrow(); });
});
